// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Alert struct {
	ID             uuid.UUID
	Token          string
	TargetPrice    string
	Direction      string
	CallbackUrl    string
	CallbackSecret string
	Triggered      bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
