// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (token, target_price, direction, callback_url, callback_secret)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, target_price, direction, callback_url, callback_secret, triggered, created_at, updated_at
`

type CreateAlertParams struct {
	Token          string
	TargetPrice    string
	Direction      string
	CallbackUrl    string
	CallbackSecret string
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, createAlert,
		arg.Token,
		arg.TargetPrice,
		arg.Direction,
		arg.CallbackUrl,
		arg.CallbackSecret,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.TargetPrice,
		&i.Direction,
		&i.CallbackUrl,
		&i.CallbackSecret,
		&i.Triggered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlert = `-- name: DeleteAlert :execresult
DELETE FROM alerts WHERE id = $1 AND triggered = FALSE
`

func (q *Queries) DeleteAlert(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAlert, id)
}

const getActiveAlerts = `-- name: GetActiveAlerts :many
SELECT id, token, target_price, direction, callback_url, callback_secret, triggered, created_at, updated_at FROM alerts WHERE triggered = FALSE
`

func (q *Queries) GetActiveAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, getActiveAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.TargetPrice,
			&i.Direction,
			&i.CallbackUrl,
			&i.CallbackSecret,
			&i.Triggered,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, token, target_price, direction, callback_url, triggered, created_at, updated_at
FROM alerts
WHERE ($1::BOOLEAN IS NULL OR triggered = $1::BOOLEAN)
ORDER BY created_at DESC
`

type ListAlertsRow struct {
	ID          uuid.UUID
	Token       string
	TargetPrice string
	Direction   string
	CallbackUrl string
	Triggered   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListAlerts(ctx context.Context, triggered sql.NullBool) ([]ListAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlerts, triggered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsRow
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.TargetPrice,
			&i.Direction,
			&i.CallbackUrl,
			&i.Triggered,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertTriggered = `-- name: MarkAlertTriggered :exec
UPDATE alerts SET triggered = TRUE, updated_at = now() WHERE id = $1
`

func (q *Queries) MarkAlertTriggered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAlertTriggered, id)
	return err
}
